services:
  app:
    build: .
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
